###
POST http://localhost:9090/api/v1/users/signup
Content-Type: application/json

{
  "email": "socurites@gmail.com",
  "password": "1234",
  "username": "socurites"
}

###
POST http://localhost:9090/api/v1/users/signin
Content-Type: application/json

{
  "email": "socurites@gmail.com",
  "password": "1234"
}