###
POST http://localhost:9090/api/v1/users/signup
Content-Type: application/json

{
  "email": "socurites@gmail.com",
  "password": "1234",
  "username": "socurites"
}

###
POST http://localhost:9090/api/v1/users/signin
Content-Type: application/json

{
  "email": "socurites@gmail.com",
  "password": "1234"
}

###
DELETE http://localhost:9090/api/v1/users/signout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhdXRoIiwiaXNzIjoidG1kIiwiZXhwIjoxNzE3NjcxMjQzLCJpYXQiOjE3MTc2Njc2NDMsInVzZXJJZCI6MSwiZW1haWwiOiJzb2N1cml0ZXNAZ21haWwuY29tIiwidXNlcm5hbWUiOiJzb2N1cml0ZXMifQ.n6dhLFKtlx5j8l4vv8TOgllLylhE2Qr0vNVQbEl97L8

###
GET http://localhost:9090/api/v1/users/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhdXRoIiwiaXNzIjoidG1kIiwiZXhwIjoxNzE3NjcxMjQzLCJpYXQiOjE3MTc2Njc2NDMsInVzZXJJZCI6MSwiZW1haWwiOiJzb2N1cml0ZXNAZ21haWwuY29tIiwidXNlcm5hbWUiOiJzb2N1cml0ZXMifQ.n6dhLFKtlx5j8l4vv8TOgllLylhE2Qr0vNVQbEl97L8