###
POST http://localhost:8080/api/v1/issues
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhdXRoIiwiaXNzIjoidG1kIiwiZXhwIjoxNzE3NjcxMjQzLCJpYXQiOjE3MTc2Njc2NDMsInVzZXJJZCI6MSwiZW1haWwiOiJzb2N1cml0ZXNAZ21haWwuY29tIiwidXNlcm5hbWUiOiJzb2N1cml0ZXMifQ.n6dhLFKtlx5j8l4vv8TOgllLylhE2Qr0vNVQbEl97L8

{
  "summary": "테스트",
  "description": "테스트",
  "type": "TASK",
  "priority": "LOW",
  "status": "TODO"
}

###
GET http://localhost:8080/api/v1/issues
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhdXRoIiwiaXNzIjoidG1kIiwiZXhwIjoxNzE3NjcxMjQzLCJpYXQiOjE3MTc2Njc2NDMsInVzZXJJZCI6MSwiZW1haWwiOiJzb2N1cml0ZXNAZ21haWwuY29tIiwidXNlcm5hbWUiOiJzb2N1cml0ZXMifQ.n6dhLFKtlx5j8l4vv8TOgllLylhE2Qr0vNVQbEl97L8

###
GET http://localhost:8080/api/v1/issues/1

###
PUT http://localhost:8080/api/v1/issues/1
Content-Type: application/json

{
  "summary": "테스트",
  "description": "테스트",
  "type": "BUG",
  "priority": "HIGH",
  "status": "IN_PROGRESS"
}

###
DELETE http://localhost:8080/api/v1/issues/1