###
POST http://localhost:8080/api/v1/issues
Content-Type: application/json

{
  "summary": "테스트",
  "description": "테스트",
  "type": "TASK",
  "priority": "LOW",
  "status": "TODO"
}

###
GET http://localhost:8080/api/v1/issues

###
GET http://localhost:8080/api/v1/issues/1

###
PUT http://localhost:8080/api/v1/issues/1
Content-Type: application/json

{
  "summary": "테스트",
  "description": "테스트",
  "type": "BUG",
  "priority": "HIGH",
  "status": "IN_PROGRESS"
}

###
DELETE http://localhost:8080/api/v1/issues/1